stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - src/preprocess.py
    - data/raw/data.csv
    outs:
    - data/processed/data.csv
    params:
    - preprocess.input
    - preprocess.output
  train:
    cmd: python src/train.py
    deps:
    - data/raw/data.csv
    - src/train.py
    params:
    - train.data
    - train.max_depth
    - train.model
    - train.n_estimators
    - train.random_state
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/raw/data.csv
    - models/model.pkl
    - src/evaluate.py
